### ISSUE TITLE
jre version

### ISSUE THREAD

**Issue by zainryan** [harry5z/Sanguosha#2]
Hey, I am very interesting in your project. However, when I import your project in eclipse, it shows lots of error. What's your jre version? Mine is 1.8.0.77.

**Comment by harry5z** [comment]
Hi @zainryan, thanks for your interest. I'm not actively working on this, as it's sorta my practice project. It's normal to see a whole lot of errors because those are residuals from an earlier and very bad design, so you may as well delete all of them.

You should still be able to run the Server.java and a bunch of Client.java tho.
